import { describe, it, expect } from "vitest";
import { snapshot } from "../src/index.js";

describe("snapshot", () => {
  it("generates CREATE TABLE SQL", () => {
    const sql = snapshot({
      todos: {
        id: "text primary key",
        text: "text not null",
        completed: "integer default 0",
      },
    });

    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "todos"');
    expect(sql).toContain('"id" TEXT PRIMARY KEY');
    expect(sql).toContain('"text" TEXT NOT NULL');
    expect(sql).toContain("DEFAULT 0");
  });

  it("generates multi-table SQL", () => {
    const sql = snapshot({
      users: { id: "text primary key", email: "text unique not null" },
      posts: { id: "text primary key", title: "text not null" },
    });

    expect(sql).toContain('"users"');
    expect(sql).toContain('"posts"');
    expect(sql.split("CREATE TABLE").length).toBe(3); // header + 2 tables
  });

  it("includes indexes", () => {
    const sql = snapshot({
      posts: {
        id: "text primary key",
        author_id: "text not null",
        status: "text",
        _indexes: ["author_id", "status"],
      },
    } as any);

    expect(sql).toContain('CREATE INDEX IF NOT EXISTS "idx_posts_author_id"');
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS "idx_posts_status"');
  });

  it("includes composite indexes", () => {
    const sql = snapshot({
      posts: {
        id: "text primary key",
        status: "text",
        created_at: "text",
        _indexes: ["status, created_at"],
      },
    } as any);

    expect(sql).toContain('"idx_posts_status_created_at"');
    expect(sql).toContain('("status", "created_at")');
  });

  it("includes header comment", () => {
    const sql = snapshot({ t: { id: "text primary key" } });

    expect(sql).toContain("Generated by d1-schema snapshot");
  });

  it("produces valid SQL (can be executed)", async () => {
    const { createMockD1 } = await import("./d1-mock.js");
    const db = createMockD1();

    const sql = snapshot({
      users: {
        id: "text primary key",
        email: "text unique not null",
        name: "text not null",
      },
      posts: {
        id: "text primary key",
        author_id: "text not null",
        title: "text not null",
        _indexes: ["author_id"],
      },
    } as any);

    // Execute the snapshot SQL — should not throw
    for (const stmt of sql.split(";").filter((s) => s.trim())) {
      await db.prepare(stmt.trim()).run();
    }

    // Verify tables exist
    await db.prepare("INSERT INTO users (id, email, name) VALUES ('1', 'a@b.com', 'Alice')").run();
    await db.prepare("INSERT INTO posts (id, author_id, title) VALUES ('1', '1', 'Hello')").run();

    const user = await db.prepare("SELECT * FROM users WHERE id = '1'").first<any>();
    expect(user.email).toBe("a@b.com");
  });

  it("handles empty schema", () => {
    const sql = snapshot({});
    expect(sql).toContain("Generated by d1-schema");
  });
});
