import type { SchemaDefinition } from "./types.js";
import { parseTableDef } from "./parse.js";
import { buildCreateTable, buildCreateIndex, escapeIdent } from "./ddl.js";

/**
 * Generate a SQL migration file from a schema definition.
 * This is the "graduation path" — when a team outgrows auto-migration,
 * they can snapshot the current schema into a versioned SQL file.
 *
 * @example
 * ```ts
 * import { snapshot } from "d1-schema";
 *
 * const sql = snapshot({
 *   todos: {
 *     id: "text primary key",
 *     text: "text not null",
 *     completed: "integer default 0",
 *     _indexes: ["completed"],
 *   },
 * });
 * // Returns a complete SQL migration string
 * ```
 */
export function snapshot(schema: SchemaDefinition): string {
  const lines: string[] = [
    `-- Generated by d1-schema snapshot`,
    `-- ${new Date().toISOString()}`,
    ``,
  ];

  for (const [tableName, tableDef] of Object.entries(schema)) {
    // Extract _indexes
    const indexes: string[] = (tableDef as any)._indexes ?? [];
    const columns: Record<string, string> = {};
    for (const [key, val] of Object.entries(tableDef)) {
      if (key !== "_indexes") columns[key] = val as string;
    }

    const parsed = parseTableDef(columns);
    lines.push(`${buildCreateTable(tableName, parsed)};`);
    lines.push(``);

    for (const idx of indexes) {
      lines.push(`${buildCreateIndex(tableName, idx)};`);
    }

    if (indexes.length > 0) lines.push(``);
  }

  return lines.join("\n").trim() + "\n";
}
